version: '3'
services:
  db:
    image: postgres:14.2-alpine
    container_name: demo-postgres-14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=your_app_name_production
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=6593
    ports:
      - "5432:5432"
  demo-web:
    build: .
    command: "./bin/rails server"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=your_app_name_production
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=6593
      - RAILS_MASTER_KEY=d885d64722a32a901f850bf58eb838a5
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - db
    ports:
      - "3005:3000"

  demo-web-2:
    build: .
    command: "./bin/rails server -p 3000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=your_app_name_production
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=6593
      - RAILS_MASTER_KEY=d885d64722a32a901f850bf58eb838a5
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - db
    ports:
      - "3002:3000"  # Expose Rails app on port 3002

  demo-web-3:
    build: .
    command: "./bin/rails server -p 3000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=your_app_name_production
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=6593
      - RAILS_MASTER_KEY=d885d64722a32a901f850bf58eb838a5
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - db
    ports:
      - "3003:3000"

volumes:
  postgres_data: {}
  app-storage: {}
