default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  port: 5432
  username: root
  password: 6593

development:
  <<: *default
  database: your_app_name_development
  host: db
  port: 5432
  username: root
  password: 6593

test:
  <<: *default
  database: your_app_name_test

production:
  <<: *default
  database: your_app_name_production
  host: db
  port: 5432
  username: root
  password: 6593
